import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
let now=100000;
class Clock extends Date {static now(){return now;}}
const requests=[];
let live=true,blocked=false,tokenMissing=false,pageCalls=0,invalidManifest=false,denyNextPage=false;
const stream=(count)=>({id:'broadcast',title:'中文直播',viewersCount:count,previewImageURL:'https://static-cdn.jtvnw.net/test.jpg',game:{name:'遊戲'}});
const user=(login,count)=>({id:'id-'+login,login,displayName:'主播'+login,profileImageURL:'https://static-cdn.jtvnw.net/avatar.jpg',lastBroadcast:{title:'已下播'},stream:live?stream(count):null});
const c=vm.createContext({Date:Clock,Host:{raise(code,message){const e=new Error(message);e.code=code;throw e;},http:{async request(input){
  requests.push(input);const {url,body}=input.request;
  if(blocked)return {status:403,bodyText:''};
  if(url.startsWith('https://usher.ttvnw.net/'))return {status:200,bodyText:invalidManifest?'invalid':'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=10,RESOLUTION=1920x1080,FRAME-RATE=60\nhttps://video.ttvnw.net/full.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=1\nhttps://video.ttvnw.net/audio.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=1\nhttps://evil.invalid/fake.m3u8\n'};
  const {query,variables}=JSON.parse(body);let data;
  if(denyNextPage&&query.includes('after:'))return {status:200,bodyText:JSON.stringify({errors:[{message:'failed integrity check',extensions:{code:'IntegrityCheckFailed'}}]})};
  if(query.includes('streams(first')){pageCalls++;const later=query.includes('after:');const u=user(later?'hot':'cool',later?2000:100);data={streams:{edges:[{cursor:later?'last':'next',node:{...u.stream,broadcaster:u}}],pageInfo:{hasNextPage:!later}}};}
  else if(query.includes('streamPlaybackAccessToken'))data={streamPlaybackAccessToken:tokenMissing?null:{value:'{"allowed":true}',signature:'sig'}};
  else if(query.includes('searchFor'))data={searchFor:{channels:{edges:[{item:user('hot',2000)},{item:{...user('offline',0),stream:null}}]}}};
  else data={user:variables.login==='missing'?null:user(variables.login,100)};
  return {status:200,bodyText:JSON.stringify({data})};
}}}});
vm.runInContext(await fs.readFile(new URL('../plugins/twitch-live/index.js',import.meta.url),'utf8'),c);
const p=c.LiveParsePlugin;
assert.equal((await p.getCategories())[0].subList[0].id,'global');
const [a,b]=await Promise.all([p.getRooms({id:'zh',page:1}),p.getRooms({id:'zh',page:1})]);
assert.equal(a.length,2);assert.equal(b[0].roomId,'hot');assert.equal(a[0].liveType,'twitch-live');assert.equal(pageCalls,2);
assert.equal((await p.getRooms({id:'zh',page:2})).length,0);
now+=61000;denyNextPage=true;const limited=await p.getRooms({id:'zh'});assert.equal(limited.length,1,'keep valid first page if anonymous continuation is denied');denyNextPage=false;
assert.ok(requests.some(r=>r.request.body?.includes('languages:[ZH]')));
requests.length=0;await p.getRooms({});assert.equal(pageCalls,5);assert.ok(requests.every(r=>!r.request.body.includes('languages')),'default directory is not language restricted');await p.getRooms({id:'global'});assert.equal(pageCalls,5,'default and global share one cache');
assert.equal((await p.search({keyword:'中文'})).length,1);
assert.equal((await p.resolveShare({shareCode:'https://www.twitch.tv/HOT?ref=test'})).roomId,'hot');
for(const input of ['https://twitch.tv.evil.invalid/hot','hot\r\nJOIN #bad','https://twitch.tv/videos/123','https://twitch.tv/hot/clip/123'])await assert.rejects(p.resolveShare({shareCode:input}),{code:'INVALID_ARGS'});
let groups=await p.getPlayback({roomId:'hot'});assert.equal(groups[0].qualitys.length,3);assert.equal(groups[0].qualitys[0].title,'HLS 自動畫質');
assert.equal(groups[0].qualitys[1].title,'HLS 1080p60');
live=false;assert.equal(await p.getLiveState({roomId:'hot'}),'0');await assert.rejects(p.getPlayback({roomId:'hot'}),{code:'NOT_FOUND'});live=true;
tokenMissing=true;await assert.rejects(p.getPlayback({roomId:'hot'}),{code:'BLOCKED'});tokenMissing=false;
invalidManifest=true;await assert.rejects(p.getPlayback({roomId:'hot'}),{code:'UPSTREAM'});invalidManifest=false;
blocked=true;await assert.rejects(p.getRoomDetail({roomId:'hot'}),{code:'BLOCKED'});blocked=false;
await assert.rejects(p.getRoomDetail({roomId:'missing'}),{code:'NOT_FOUND'});
const plan=await p.getDanmaku({roomId:'hot'});assert.equal(plan.transport.kind,'websocket');
await p.createDanmakuSession({connectionId:'c',args:plan.args});
const open=await p.onDanmakuOpen({connectionId:'c'});assert.ok(open.writes.some(w=>w.text==='PASS SCHMOOPIIE\r\n'));assert.ok(open.writes.some(w=>w.text.startsWith('NICK justinfan')));
const frame=text=>p.onDanmakuFrame({connectionId:'c',frameType:'text',text});
let r=await frame(':tmi.twitch.tv 001 justinfan123 :Welcome\r\n');assert.equal(r.writes[0].text,'JOIN #hot\r\n');
r=await frame('PING :tmi.twitch.tv\r\n@room-id=1 :tmi.twitch.tv ROOMSTATE #hot\r\n');assert.equal(r.writes[0].text,'PONG :tmi.twitch.tv\r\n');
assert.equal((await frame('@id=first;display-name=測試\\s主播 :test!test@test.tmi.twitch.tv PRIVMSG #hot :訊息')).messages.length,0);
r=await frame('\r\n@id=first :test!t@t PRIVMSG #hot :重複\r\n@id=wrong :test!t@t PRIVMSG #other :別的頻道\r\n@id=second;display-name=甲\\:乙 :test!t@t PRIVMSG #hot :\x01ACTION 揮手\x01\r\n');
assert.equal(r.messages.length,2);assert.equal(r.messages[0].nickname,'測試 主播');assert.equal(r.messages[1].text,'揮手');assert.equal(r.messages[1].nickname,'甲;乙');
assert.ok((await p.onDanmakuTick({connectionId:'c'})).writes[0].text.startsWith('PING'));
await assert.rejects(frame(':tmi.twitch.tv RECONNECT\r\n'),{code:'NETWORK'});
now+=91000;await assert.rejects(p.onDanmakuTick({connectionId:'c'}),{code:'NETWORK'});
await p.destroyDanmakuSession({connectionId:'c'});await assert.rejects(p.onDanmakuTick({connectionId:'c'}),{code:'INVALID_ARGS'});
await p.createDanmakuSession({connectionId:'c',roomId:'hot'});now+=46000;await assert.rejects(p.onDanmakuTick({connectionId:'c'}),{code:'NETWORK'});
await assert.rejects(frame(':tmi.twitch.tv NOTICE * :Login authentication failed\r\n'),{code:'BLOCKED'});
assert.ok(requests.every(r=>r.authMode==='none'&&r.platformId==='twitch-live'));
console.log('twitch contract: OK (pagination, global default + Chinese discovery, playback, state, IRC tags/fragmentation/dedupe/keepalive/reconnect)');
